### ISSUE TITLE
Search how to determine how dangerous it is

### ISSUE THREAD

**Issue by Meerkath** [diallorg/Projet-HackathonOneM2M2021#12]
Search for an algorithm that can determine the dangerousness of a sensor based on the last humidity, temperatures, fire, and wind speed data.

**Comment by rubypillar** [comment]
=2*10^(-0,45+0,987*LN(DF)-0,0345*H+0,0338*T+0,0234*W)
DF: Drought factor
H: Humidity in %
T:Temperature in c°
W: Wind speed in km/h

**Comment by rubypillar** [comment]
https://wikifire.wsl.ch/tiki-index27fc.html?page=McArthur+Mark+5+forest+fire+danger+index
